# Function extension config. `spend-save` is replaced by the generator.
api_version = "2025-01"

[[extensions]]
name = "Spend and Save"
handle = "spend-save-discount"
type = "function"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.metafields]
  namespace = "$app:settings"
  key = "config"
