# Per-product quantity-limit validation Function. `product-limits` replaced by generator.
api_version = "2025-01"

[[extensions]]
name = "Per Product Limits"
handle = "product-limits-validation"
type = "function"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.metafields]
  namespace = "$app:settings"
  key = "config"
