# Payment customization Function. `hide-payment` is replaced by the generator.
api_version = "2025-01"

[[extensions]]
name = "Hide Payment Method"
handle = "hide-payment-payment"
type = "function"

  [[extensions.targeting]]
  target = "purchase.payment-customization.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.metafields]
  namespace = "$app:settings"
  key = "config"
